# Generated by Django 5.1.1 on 2024-09-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='닉네임')),
                ('gender', models.BooleanField(null=True, verbose_name='성별')),
                ('birth', models.DateField(null=True, verbose_name='생일')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('login_type', models.CharField(choices=[('naver', '네이버'), ('kakao', '카카오'), ('apple', '애플')], max_length=50, verbose_name='로그인 방식')),
                ('profile_image', models.URLField(max_length=500, null=True, verbose_name='프로필 이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
            },
        ),
    ]
