repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
    - id: black
      args: ['-l', '140', '-t', 'py312']

default_language_version:
  python: python3.12
