version: '3.8'

services:

  backend:
    container_name: web
    build:
      context: .
      dockerfile: prod.Dockerfile
    entrypoint:
      - sh
      - -c
      - |
        poetry run python manage.py migrate &&
        poetry run gunicorn config.wsgi.dev -b 0.0.0.0:8000
    volumes:
      - ./backend/django/:/app/
      - /etc/localtime:/etc/localtime:ro
      - django_media:/app/media/
      - django_static:/app/static/
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    expose:
      - "8000"
    restart: always


volumes:
  static:
  media: