version: '3'

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./docker/prod.Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    depends_on:
      - redis
    entrypoint:
      - sh
      - ./scripts/entrypoint.prod.sh

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    container_name: nginx
    build: ./nginx/
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
  media:
  redis-data:
