version: '3'

services:
  web:
    container_name: web-dev
    build:
      context: ./
      dockerfile: ./docker/dev.Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      LOCAL_MYSQL_HOST: host.docker.internal
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    entrypoint:
      - sh
      - ./scripts/entrypoint.dev.sh

  redis:
    container_name: redis-dev
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
