version: '3.8'
volumes:
  mysqldata:

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.39
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=brewbuds
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: on-failure

  django:
    container_name: django
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    entrypoint:
      - sh
      - -c
      - |
        poetry run python manage.py migrate &&
        poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    restart: on-failure