# Generated by Django 5.1.4 on 2025-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsetting",
            name="comment_notify",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notificationsetting",
            name="follow_notify",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notificationsetting",
            name="like_notify",
            field=models.BooleanField(default=False),
        ),
    ]
