# Generated by Django 5.1.1 on 2024-09-24 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beans', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean_taste_and_review',
            name='taste_review_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.tasted_record', verbose_name='시음기록'),
        ),
    ]
