# Generated by Django 5.1.4 on 2025-01-17 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Report",
            new_name="ContentReport",
        ),
        migrations.AlterModelOptions(
            name="contentreport",
            options={
                "verbose_name": "콘텐츠 신고",
                "verbose_name_plural": "콘텐츠 신고",
            },
        ),
        migrations.AlterModelTable(
            name="contentreport",
            table="content_report",
        ),
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="신고 사유")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("processing", "처리 중"),
                            ("completed", "완료됨"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="신고 처리 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신고 일자"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고 대상 유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "유저 신고",
                "verbose_name_plural": "유저 신고",
                "db_table": "user_report",
            },
        ),
    ]
