# Generated by Django 5.1.2 on 2024-10-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0005_alter_post_tasted_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tasted_records",
            field=models.ManyToManyField(blank=True, related_name="posts", to="records.tastedrecord", verbose_name="관련 시음 기록"),
        ),
    ]
