# Generated by Django 5.1.2 on 2024-10-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_alter_photo_photo_url"),
        ("records", "0006_alter_post_tasted_records"),
    ]

    operations = []
