# Generated by Django 5.1.2 on 2024-10-30 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_squashed_0008_alter_photo_photo_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="subject",
            field=models.CharField(
                choices=[
                    ("일반", "normal"),
                    ("카페", "cafe"),
                    ("원두", "bean"),
                    ("정보", "info"),
                    ("질문", "question"),
                    ("고민", "worry"),
                    ("장비", "gear"),
                ],
                max_length=100,
                verbose_name="주제",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("post", "게시글"),
                            ("comment", "댓글"),
                            ("tasted_record", "시음 기록"),
                        ],
                        max_length=50,
                        verbose_name="신고 대상 종류",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="신고 대상 ID")),
                ("reason", models.TextField(verbose_name="신고 사유")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("processing", "처리 중"),
                            ("completed", "완료됨"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="신고 처리 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신고 일자"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "신고",
                "verbose_name_plural": "신고",
                "db_table": "report",
            },
        ),
    ]
