# Generated by Django 5.1.2 on 2025-01-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0009_alter_post_subject_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="author",
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="records/%Y/%m/%d/",
                verbose_name="사진",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="subject",
            field=models.CharField(
                choices=[
                    ("normal", "일반"),
                    ("cafe", "카페"),
                    ("bean", "원두"),
                    ("info", "정보"),
                    ("question", "질문"),
                    ("worry", "고민"),
                    ("gear", "장비"),
                ],
                max_length=100,
                verbose_name="주제",
            ),
        ),
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
