# Generated by Django 5.1.4 on 2025-01-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0010_remove_report_author_alter_photo_photo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tastedrecord",
            name="tasted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시음일"),
        ),
    ]
