# Generated by Django 5.1.4 on 2025-01-23 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0012_alter_tastedrecord_tasted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="like_cnt",
            field=models.ManyToManyField(blank=True, related_name="like_posts", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="tastedrecord",
            name="like_cnt",
            field=models.ManyToManyField(
                blank=True,
                related_name="like_tasted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
