# Generated by Django 5.1.4 on 2025-01-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0013_alter_post_like_cnt_alter_tastedrecord_like_cnt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tastedrecord",
            name="tasted_at",
        ),
    ]
