# Generated by Django 5.1.4 on 2025-01-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0015_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="좋아요 수"),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: update_likes_field(apps, schema_editor, "Comment"),
            reverse_code=lambda apps, schema_editor: update_likes_field(apps, schema_editor, "Comment", reverse=True),
        ),
        migrations.AddField(
            model_name="tastedrecord",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="좋아요 수"),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: update_likes_field(apps, schema_editor, "TastedRecord"),
            reverse_code=lambda apps, schema_editor: update_likes_field(apps, schema_editor, "TastedRecord", reverse=True),
        ),
    ]


def update_likes_field(apps, schema_editor, model: str, reverse=False):
    model = apps.get_model("records", model)
    if reverse:
        model.objects.all().update(likes=0)
    else:
        for item in model.objects.all():
            item.likes = item.like_cnt.count()
            item.save()
