# Generated by Django 5.1.4 on 2025-11-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0016_comment_likes_tastedrecord_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionLogRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data_1", models.TextField(verbose_name="입력 데이터 1")),
                ("input_data_2", models.TextField(verbose_name="입력 데이터 2")),
                ("input_data_3", models.TextField(verbose_name="입력 데이터 3")),
                ("input_data_4", models.TextField(verbose_name="입력 데이터 4")),
                ("input_data_5", models.TextField(verbose_name="입력 데이터 5")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "db_table": "exception_log_record",
            },
        ),
    ]
