# Generated by Django 5.1.1 on 2024-09-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_remove_post_like_cnt_remove_tasted_record_like_cnt_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="likes",
            new_name="like_cnt",
        ),
        migrations.RenameField(
            model_name="tasted_record",
            old_name="likes",
            new_name="like_cnt",
        ),
    ]
