# Generated by Django 5.1.4 on 2025-11-08 15:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalEvent",
            fields=[
                (
                    "event_key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="이벤트 키",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "진행 전"),
                            ("active", "진행 중"),
                            ("done", "종료"),
                        ],
                        default="ready",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.CharField(max_length=255, verbose_name="내용")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_icons/",
                        verbose_name="아이콘",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="우선순위 (높을수록 우선)",
                        verbose_name="우선순위",
                    ),
                ),
                ("condition", models.JSONField(verbose_name="달성 조건")),
            ],
            options={
                "verbose_name": "내부조건형 이벤트",
                "verbose_name_plural": "내부조건형 이벤트",
                "db_table": "internal_events",
                "ordering": ["-priority", "event_key"],
            },
        ),
        migrations.CreateModel(
            name="PromotionalEvent",
            fields=[
                (
                    "event_key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="이벤트 키",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "진행 전"),
                            ("active", "진행 중"),
                            ("done", "종료"),
                        ],
                        default="ready",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "is_commercial",
                    models.BooleanField(default=False, verbose_name="상업 여부"),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="업체명"),
                ),
                ("purpose", models.CharField(max_length=20, verbose_name="목적")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                ("start_date", models.DateTimeField(verbose_name="시작일")),
                ("end_date", models.DateTimeField(verbose_name="종료일")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_icons/",
                        verbose_name="아이콘",
                    ),
                ),
                (
                    "external_link",
                    models.URLField(verbose_name="외부링크 (캠페인 URL)"),
                ),
            ],
            options={
                "verbose_name": "프로모션형 이벤트",
                "verbose_name_plural": "프로모션형 이벤트",
                "db_table": "promotional_events",
                "ordering": ["event_key"],
                "indexes": [
                    models.Index(
                        fields=["status", "start_date", "end_date"],
                        name="promotional_status_9fac42_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internal_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="completions",
                        to="events.internalevent",
                    ),
                ),
                (
                    "promotional_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="completions",
                        to="events.promotionalevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "이벤트 완료 기록",
                "verbose_name_plural": "이벤트 완료 기록",
                "db_table": "event_completions",
                "indexes": [
                    models.Index(
                        fields=["user", "internal_event"],
                        name="event_compl_user_id_97b71e_idx",
                    ),
                    models.Index(
                        fields=["user", "promotional_event"],
                        name="event_compl_user_id_655083_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("internal_event__isnull", False),
                                ("promotional_event__isnull", True),
                            ),
                            models.Q(
                                ("internal_event__isnull", True),
                                ("promotional_event__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="only_one_event_type",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("promotional_event__isnull", False)),
                        fields=("user", "promotional_event"),
                        name="unique_user_promotional_event",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("internal_event__isnull", False)),
                        fields=("user", "internal_event"),
                        name="unique_user_internal_event",
                    ),
                ],
            },
        ),
    ]
