# Generated by Django 5.1.4 on 2025-11-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcompletion",
            name="content",
            field=models.JSONField(blank=True, default=dict, verbose_name="폼 제출 내용"),
        ),
        migrations.AddField(
            model_name="eventcompletion",
            name="is_agree",
            field=models.BooleanField(default=True, verbose_name="사용자 동의 여부"),
        ),
        migrations.AlterField(
            model_name="eventcompletion",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="완료 시간"),
        ),
        migrations.AlterField(
            model_name="internalevent",
            name="event_key",
            field=models.CharField(
                help_text="projectID를 입력하세요",
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="이벤트 키",
            ),
        ),
        migrations.AlterField(
            model_name="promotionalevent",
            name="event_key",
            field=models.CharField(
                help_text="projectID를 입력하세요",
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="이벤트 키",
            ),
        ),
    ]
