# Generated by Django 5.1.4 on 2025-11-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventcompletion_content_eventcompletion_is_agree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcompletion",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="사용자 전화번호"),
        ),
    ]
