# Generated by Django 5.1.4 on 2025-11-23 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_eventcompletion_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventcompletion",
            name="only_one_event_type",
        ),
        migrations.RemoveConstraint(
            model_name="eventcompletion",
            name="unique_user_promotional_event",
        ),
        migrations.RemoveConstraint(
            model_name="eventcompletion",
            name="unique_user_internal_event",
        ),
        migrations.RemoveIndex(
            model_name="eventcompletion",
            name="event_compl_user_id_97b71e_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventcompletion",
            name="event_compl_user_id_655083_idx",
        ),
        migrations.RenameField(
            model_name="eventcompletion",
            old_name="internal_event",
            new_name="internal",
        ),
        migrations.RenameField(
            model_name="eventcompletion",
            old_name="promotional_event",
            new_name="promotional",
        ),
        migrations.AddIndex(
            model_name="eventcompletion",
            index=models.Index(fields=["user", "internal"], name="event_compl_user_id_c0f730_idx"),
        ),
        migrations.AddIndex(
            model_name="eventcompletion",
            index=models.Index(fields=["user", "promotional"], name="event_compl_user_id_12f5c0_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventcompletion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("internal__isnull", False), ("promotional__isnull", True)),
                    models.Q(("internal__isnull", True), ("promotional__isnull", False)),
                    _connector="OR",
                ),
                name="only_one_event_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventcompletion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("promotional__isnull", False)),
                fields=("user", "promotional"),
                name="unique_user_promotional_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventcompletion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("internal__isnull", False)),
                fields=("user", "internal"),
                name="unique_user_internal_event",
            ),
        ),
    ]
