# Generated by Django 5.1.2 on 2024-10-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beantastereview",
            name="star",
            field=models.FloatField(
                choices=[
                    (0.0, 0.0),
                    (0.5, 0.5),
                    (1.0, 1.0),
                    (1.5, 1.5),
                    (2.0, 2.0),
                    (2.5, 2.5),
                    (3.0, 3.0),
                    (3.5, 3.5),
                    (4.0, 4.0),
                    (4.5, 4.5),
                    (5.0, 5.0),
                ],
                verbose_name="별점",
            ),
        ),
    ]
