# Generated by Django 5.1.2 on 2024-11-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0002_alter_beantastereview_star"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bean",
            name="bev_type",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="음료 유형"),
        ),
        migrations.AlterField(
            model_name="bean",
            name="extraction",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="추출 방식"),
        ),
        migrations.AlterField(
            model_name="bean",
            name="is_user_created",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="사용자 추가 여부"),
        ),
        migrations.AlterField(
            model_name="bean",
            name="process",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="가공 방식"),
        ),
        migrations.AlterField(
            model_name="bean",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="지역"),
        ),
        migrations.AlterField(
            model_name="bean",
            name="roast_point",
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="로스팅 포인트",
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="roastery",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="로스터리"),
        ),
        migrations.AlterField(
            model_name="bean",
            name="variety",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="원두 품종"),
        ),
    ]
