# Generated by Django 5.1.2 on 2025-01-12 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0003_alter_bean_bev_type_alter_bean_extraction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bean",
            name="is_official",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="공식원두 여부"),
        ),
        migrations.CreateModel(
            name="OfficialBean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="beans/images/",
                        verbose_name="공식원두 이미지",
                    ),
                ),
                (
                    "bean_type",
                    models.CharField(
                        choices=[("single", "싱글 오리진"), ("blend", "블랜드")],
                        max_length=20,
                        verbose_name="원두 유형",
                    ),
                ),
                (
                    "is_decaf",
                    models.BooleanField(default=False, verbose_name="디카페인"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="원두명")),
                (
                    "origin_country",
                    models.CharField(max_length=100, verbose_name="원산지"),
                ),
                (
                    "extraction",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="추출 방식"),
                ),
                (
                    "roast_point",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="로스팅 포인트",
                    ),
                ),
                (
                    "process",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="가공 방식"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="지역"),
                ),
                (
                    "bev_type",
                    models.BooleanField(blank=True, default=False, null=True, verbose_name="음료 유형"),
                ),
                (
                    "roastery",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="로스터리"),
                ),
                (
                    "variety",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="원두 품종"),
                ),
                (
                    "is_user_created",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="사용자 추가 여부",
                    ),
                ),
                (
                    "bean_taste",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_bean",
                        to="beans.beantaste",
                        verbose_name="원두 맛",
                    ),
                ),
            ],
            options={
                "verbose_name": "공식원두",
                "verbose_name_plural": "공식원두",
                "db_table": "official_bean",
            },
        ),
    ]
