# Generated by Django 5.1.4 on 2025-01-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0004_bean_is_official_officialbean"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beantaste",
            options={
                "verbose_name": "공식 원두 기본 맛",
                "verbose_name_plural": "공식 원두 기본 맛",
            },
        ),
        migrations.AddField(
            model_name="bean",
            name="image_url",
            field=models.URLField(blank=True, null=True, verbose_name="공식원두 이미지"),
        ),
        migrations.AddField(
            model_name="beantaste",
            name="bean",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bean_taste",
                to="beans.bean",
                verbose_name="공식 원두 기본 맛",
            ),
        ),
        migrations.AlterField(
            model_name="beantaste",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.DeleteModel(
            name="OfficialBean",
        ),
    ]
