# Generated by Django 5.1.4 on 2025-01-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0005_alter_beantaste_options_bean_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beantastereview",
            name="created_at",
        ),
        migrations.AddField(
            model_name="beantastereview",
            name="tasted_at",
            field=models.DateField(blank=True, null=True, verbose_name="시음일"),
        ),
    ]
