# Generated by Django 5.1.4 on 2025-01-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0006_remove_beantastereview_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotUsedBean",
            fields=[],
            options={
                "verbose_name": "사용하지 않는 원두",
                "verbose_name_plural": "사용하지 않는 원두",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("beans.bean",),
        ),
    ]
