# Generated by Django 5.1.4 on 2025-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0008_alter_beantaste_bean"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beantastereview",
            name="place",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="시음 장소"),
        ),
    ]
