# Generated by Django 5.1.2 on 2024-10-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.IntegerField(blank=True, null=True, verbose_name='출생 연도'),
        ),
    ]
