# Generated by Django 5.1.2 on 2024-10-10 21:23

from django.db import migrations, models

import repo.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_userdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="coffee_life",
            field=models.JSONField(default=repo.profiles.models.UserDetail.default_coffee_life, verbose_name="커피 생활"),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="preferred_bean_taste",
            field=models.JSONField(default=repo.profiles.models.UserDetail.default_taste, verbose_name="선호하는 원두 맛"),
        ),
    ]
