# Generated by Django 5.1.2 on 2024-10-18 01:21

from django.db import migrations, models

import repo.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_userdetail_coffee_life_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth",
            field=models.IntegerField(blank=True, null=True, verbose_name="출생 연도"),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="preferred_bean_taste",
            field=models.JSONField(default=repo.profiles.models.UserDetail.default_coffee_life, verbose_name="선호하는 원두 맛"),
        ),
    ]
