# Generated by Django 5.1.2 on 2024-10-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_customuser_profile_image"),
        ("profiles", "0003_alter_userdetail_coffee_life_and_more"),
    ]

    operations = []
