# Generated by Django 5.1.2 on 2024-10-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_merge_20241018_2357"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="relationship",
            managers=[],
        ),
    ]
