# Generated by Django 5.1.2 on 2024-10-21 13:08

from django.db import migrations, models

import repo.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_squashed_0006_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth",
            field=models.IntegerField(blank=True, null=True, verbose_name="출생 연도"),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="preferred_bean_taste",
            field=models.JSONField(
                default=repo.profiles.models.UserDetail.default_coffee_life,
                verbose_name="선호하는 원두 맛",
            ),
        ),
    ]
