# Generated by Django 5.1.2 on 2025-01-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_customuser_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="is_certificated",
            field=models.BooleanField(default=False, verbose_name="자격증 여부"),
        ),
        migrations.DeleteModel(
            name="Relationship",
        ),
    ]
