# Generated by Django 5.1.4 on 2025-01-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_alter_userdetail_is_certificated_delete_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="가입 일시"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="이메일",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="성별"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성 여부"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="관리자 여부"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="슈퍼 관리자 여부"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="login_type",
            field=models.CharField(
                blank=True,
                choices=[("naver", "네이버"), ("kakao", "카카오"), ("apple", "애플")],
                max_length=50,
                null=True,
                verbose_name="로그인 유형",
            ),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="introduction",
            field=models.TextField(blank=True, null=True, verbose_name="소개글"),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_detail",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
    ]
