# Generated by Django 5.1.4 on 2025-03-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0009_alter_customuser_created_at_alter_customuser_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("남", "남성"), ("여", "여성")],
                max_length=10,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
