name: Deploy to EC2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Create env file
      env:
        ENV_VARS: ${{ secrets.ENV_VARS }}
      run: |
        touch .env
        echo "$ENV_VARS" >> .env

    - name: create remote directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          mkdir -p /home/ubuntu/srv/ubuntu
          mkdir -p /home/ubuntu/srv/ubuntu/secrets
          mkdir -p /home/ubuntu/srv/ubuntu/ssl

    - name: Create FCM service account key file
      run: |
        echo '${{ secrets.FCM_KEY }}' > brew-buds-fcm-account.json
        mkdir -p secrets
        mv brew-buds-fcm-account.json secrets/

    - name: Setup SSL certificates
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          if [ ! -d "/home/ubuntu/srv/ubuntu/ssl/live" ]; then
            sudo apt-get update
            sudo apt-get install -y certbot
            sudo certbot certonly --standalone -d ${{ secrets.DOMAIN }} --agree-tos --email ${{ secrets.EMAIL }} --non-interactive
            sudo cp -r /etc/letsencrypt/live/* /home/ubuntu/srv/ubuntu/ssl/
            sudo cp -r /etc/letsencrypt/archive/* /home/ubuntu/srv/ubuntu/ssl/
          fi

    - name: copy source via ssh key
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/srv/ubuntu/
        remote_host: ${{ secrets.EC2_HOST }}
        remote_user: ubuntu
        remote_key: ${{ secrets.KEY }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          sh /home/ubuntu/srv/ubuntu/scripts/deploy.sh
